server:
  port: 7500
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: servidor-gateway
  cloud: 
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: serv-productos
          #lb:// cuando se va a acceder a través de Eureka
        uri: lb://servicios-productos1  #http://localhost:8080
        predicates:
          - Path=/sproductos/**
        filters:
          - RewritePath=/sproductos/*, /